version: '3'

services:
    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: mongo
        ports:
            - 27017:27017

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - backend 
