export const Tags = [
	{ tag: "NNG", desc: "일반 명사", color: "#804040" },
	{ tag: "NNP", desc: "고유 명사", color: "#804740" },
	{ tag: "NNB", desc: "의존 명사", color: "#804f40" },
	{ tag: "NNBC", desc: "단위를 나타내는 명사", color: "#805740" },
	{ tag: "NR", desc: "수사", color: "#805e40" },
	{ tag: "NP", desc: "대명사", color: "#806640" },
	{ tag: "VV", desc: "동사", color: "#806e40" },
	{ tag: "VA", desc: "형용사", color: "#807540" },
	{ tag: "VX", desc: "보조 용언", color: "#807d40" },
	{ tag: "VCP", desc: "긍정 지정사", color: "#7a8040" },
	{ tag: "VCN", desc: "부정 지정사", color: "#738040" },
	{ tag: "MM", desc: "관형사", color: "#6b8040" },
	{ tag: "MAG", desc: "일반 부사", color: "#638040" },
	{ tag: "MAJ", desc: "접속 부사", color: "#5c8040" },
	{ tag: "IC", desc: "감탄사", color: "#548040" },
	{ tag: "JKS", desc: "주격 조사", color: "#4d8040" },
	{ tag: "JKC", desc: "보격 조사", color: "#458040" },
	{ tag: "JKG", desc: "관형격 조사", color: "#408042" },
	{ tag: "JKO", desc: "목적격 조사", color: "#40804a" },
	{ tag: "JKB", desc: "부사격 조사", color: "#408052" },
	{ tag: "JKV", desc: "호격 조사", color: "#408059" },
	{ tag: "JKQ", desc: "인용격 조사", color: "#408061" },
	{ tag: "JC", desc: "접속 조사", color: "#408069" },
	{ tag: "JX", desc: "보조사", color: "#408070" },
	{ tag: "EP", desc: "선어말어미", color: "#408078" },
	{ tag: "EF", desc: "종결 어미", color: "#408080" },
	{ tag: "EC", desc: "연결 어미", color: "#407880" },
	{ tag: "ETN", desc: "명사형 전성 어미", color: "#407080" },
	{ tag: "ETM", desc: "관형형 전성 어미", color: "#406980" },
	{ tag: "XPN", desc: "체언 접두사", color: "#406180" },
	{ tag: "XSN", desc: "명사파생 접미사", color: "#405980" },
	{ tag: "XSV", desc: "동사 파생 접미사", color: "#405280" },
	{ tag: "XSA", desc: "형용사 파생 접미사", color: "#404a80" },
	{ tag: "XR", desc: "어근", color: "#404280" },
	{ tag: "SF", desc: "마침표, 물음표, 느낌표", color: "#454080" },
	{ tag: "SE", desc: "줄임표 …", color: "#4c4080" },
	{ tag: "SSO", desc: "여는 괄호 (, [", color: "#544080" },
	{ tag: "SSC", desc: "닫는 괄호 ), ]", color: "#5c4080" },
	{ tag: "SC", desc: "구분자 , · / :", color: "#634080" },
	{ tag: "SY", desc: "기타 기호", color: "#6b4080" },
	{ tag: "SH", desc: "한자", color: "#734080" },
	{ tag: "SL", desc: "외국어", color: "#7a4080" },
	{ tag: "SN", desc: "숫자", color: "#80407d" }
];

export const TagDesc = {
	"lemmaCnt": "전체 형태소 타입 수(NDW)",
	"lemmaTTR": "전체 형태소 다양성, 타입-토큰 비율(TTR)",
	"lemmaMTTR": "50구간별 전체 형태소 다양성, 타입-토큰 비율(TTR)",
	"contentTTR": "실질 형태소 다양성, 타입-토큰 비율(TTR)",
	"formalTTR": "형식 형태소 다양성, 타입-토큰 비율(TTR)",
	"nounTTR": "명사 다양성, 타입-토큰 비율(TTR)",
	"VVTTR": "동사 다양성, 타입-토큰 비율(TTR)",
	"VATTR": "형용사 다양성, 타입-토큰 비율(TTR)",
	"MATTR": "부사 다양성, 타입-토큰 비율(TTR)",
	"conjunctions": "접속사 다양성, 타입-토큰 비율(TTR)",
	"bigramLemmaTTR": "전체 형태소 bigram 다양성, 타입-토큰 비율(TTR)",
	"trigramLemmaTTR": "전체 형태소 trigram 다양성, 타입-토큰 비율(TTR)",
	"lexicalDensityTokens": "형태소 토큰 범위 참조 응집성",
	"lexicalDensityTypes": "형태소 타입의 참조 응집성",
	"avgSentSimilarity": "KeyBERT 주제 일관성",
	"topicConsistency": "SBERT 텍스트 내 문장 간 의미 유사도",
	"charCnt": "음절 수",
	"morphCnt": "형태소 수",
	"wordCnt": "어절 수",
	"sentenceCnt": "문장 수",
	"paraCnt": "문단 수",
	"contentCnt": "실질 형태소 수",
	"formalCnt": "형식 형태소 수",
	"substansiveCnt": "체언 수",
	"nounCnt": "명사 수",
	"NNGCnt": "일반명사 수",
	"NNPCnt": "고유명사 수",
	"NNBCnt": "의존명사 수",
	"NPCnt": "대명사 수",
	"NPPeopleCnt": "인칭대명사 수",
	"NPThingsCnt": "지시대명사 수",
	"NRCnt": "수사 수",
	"verbCnt": "용언 수",
	"VVCnt": "동사 수",
	"VACnt": "형용사 수",
	"VXCnt": "보조용언 수",
	"VCPCnt": "긍정 지정사(서술격조사) 수",
	"VCNCnt": "부정 지정사 수",
	"modCnt": "수식언 수",
	"MMCnt": "관형사 수",
	"MACnt": "부사 수",
	"JCnt": "관계언(조사) 수",
	"ECnt": "어미 수",
	"XCnt": "접사 수",
	"ICCnt": "독립언 수",
	"substansiveLst": "체언 목록",
	"nounLst": "명사 목록",
	"NNGLst": "일반명사 목록",
	"NNPLst": "고유명사 목록",
	"NNBLst": "의존명사 목록",
	"NPLst": "대명사 목록",
	"NPPeopleLst": "인칭대명사 목록",
	"NPThingsLst": "지시대명사 목록",
	"NRLst": "수사 목록",
	"verbLst": "용언 목록",
	"VVLst": "동사 목록",
	"VALst": "형용사 목록",
	"VXLst": "보조용언 목록",
	"VCPLst": "긍정 지정사(서술격조사) 목록",
	"VCNLst": "부정 지정사 목록",
	"modLst": "수식언 목록",
	"MMLst": "관형사 목록",
	"MALst": "부사 목록",
	"JLst": "조사 목록",
	"ELst": "어미 목록",
	"XLst": "접사 목록",
	"ICLst": "독립언 목록",
	"CLDen": "실질 형태소 밀도",
	"FLDen": "형식 형태소 밀도",
	"NLDen": "체언 밀도",
	"NCLDen": "체언 실질 밀도",
	"NNLDen": "명사 밀도",
	"NNCLDen": "명사 실질 밀도",
	"NNGLDen": "일반명사 밀도",
	"NNGCLDen": "일반명사 실질 밀도",
	"NNPLDen": "고유명사 밀도",
	"NNPCLDen": "고유명사 실질 밀도",
	"NNBLDen": "의존명사 밀도",
	"NNBCLDen": "의존명사 실질 밀도",
	"NPLDen": "대명사 밀도",
	"NPCLDen": "대명사 실질 밀도",
	"NMLDen": "수사 밀도",
	"NMCLDen": "수사 실질 밀도",
	"VLDen": "용언 밀도",
	"VCLDen": "용언 실질 밀도",
	"VVLDen": "동사 밀도",
	"VVCLDen": "동사 실질 밀도",
	"VALDen": "형용사 밀도",
	"VACLDen": "형용사 실질 밀도",
	"MLDen": "수식언 밀도",
	"MCLDen": "수식언 실질 밀도",
	"MMLDen": "관형사 밀도",
	"MMCLDen": "관형사 실질 밀도",
	"MALDen": "부사 밀도",
	"MACLDen": "부사 실질 밀도",
	"ITLDen": "독립언 밀도",
	"INCLDen": "독립언 실질 밀도",
	"JLDen": "조사 밀도",
	"JFLDen": "조사 형식 밀도",
	"ELDen": "어미 밀도",
	"EFLDen": "어미 형식 밀도",
	"XLDen": "접사 밀도",
	"XFLDen": "접사 형식 밀도",
	"morphLenAvg": "형태소 길이, 음절 수, 평균",
	"morphLenStd": "형태소 길이, 음절 수, 표준편차",
	"wordLenAvg": "어절 길이, 음절 수, 평균",
	"wordLenStd": "어절 길이, 음절 수, 표준편차"
}
