import React from "react";


const Tags = [
	{ "tag": "NNG", "desc": "일반 명사", "color": "#e29f6f" },
	{ "tag": "NNP", "desc": "고유 명사", "color": "#ebaa94" },
	{ "tag": "NNB", "desc": "의존 명사", "color": "#8a5d2f" },
	{ "tag": "NNBC", "desc": "단위를 나타내는 명사", "color": "#c2485e" },
	{ "tag": "NR", "desc": "수사", "color": "#fc65c1" },
	{ "tag": "NP", "desc": "대명사", "color": "#e7a9c3" },
	{ "tag": "VV", "desc": "동사", "color": "#cda5e7" },
	{ "tag": "VA", "desc": "형용사", "color": "#fa0242" },
	{ "tag": "VX", "desc": "보조 용언", "color": "#dba91f" },
	{ "tag": "VCP", "desc": "긍정 지정사", "color": "#b7ebdc" },
	{ "tag": "VCN", "desc": "부정 지정사", "color": "#a3a771" },
	{ "tag": "MM", "desc": "관형사", "color": "#c82686" },
	{ "tag": "MAG", "desc": "일반 부사", "color": "#a3c661" },
	{ "tag": "MAJ", "desc": "접속 부사", "color": "#9846d4" },
	{ "tag": "IC", "desc": "감탄사", "color": "#c0212e" },
	{ "tag": "JKS", "desc": "주격 조사", "color": "#a59f43" },
	{ "tag": "JKC", "desc": "보격 조사", "color": "#cf65d4" },
	{ "tag": "JKG", "desc": "관형격 조사", "color": "#99488d" },
	{ "tag": "JKO", "desc": "목적격 조사", "color": "#92e0c8" },
	{ "tag": "JKB", "desc": "부사격 조사", "color": "#d487ce" },
	{ "tag": "JKV", "desc": "호격 조사", "color": "#f8de58" },
	{ "tag": "JKQ", "desc": "인용격 조사", "color": "#99c78d" },
	{ "tag": "JC", "desc": "접속 조사", "color": "#da9211" },
	{ "tag": "JX", "desc": "보조사", "color": "#ef25e2" },
	{ "tag": "EP", "desc": "선어말어미", "color": "#d0f244" },
	{ "tag": "EF", "desc": "종결 어미", "color": "#b458a7" },
	{ "tag": "EC", "desc": "연결 어미", "color": "#fa1d50" },
	{ "tag": "ETN", "desc": "명사형 전성 어미", "color": "#f1545a" },
	{ "tag": "ETM", "desc": "관형형 전성 어미", "color": "#c2af9f" },
	{ "tag": "XPN", "desc": "체언 접두사", "color": "#8ff18e" },
	{ "tag": "XSN", "desc": "명사파생 접미사", "color": "#83983c" },
	{ "tag": "XSV", "desc": "동사 파생 접미사", "color": "#97e0aa" },
	{ "tag": "XSA", "desc": "형용사 파생 접미사", "color": "#e6194c" },
	{ "tag": "XR", "desc": "어근", "color": "#804ae5" },
	{ "tag": "SF", "desc": "마침표, 물음표, 느낌표", "color": "#fe5b1e" },
	{ "tag": "SE", "desc": "줄임표 …", "color": "#d54858" },
	{ "tag": "SSO", "desc": "여는 괄호 (, [", "color": "#be70f1" },
	{ "tag": "SSC", "desc": "닫는 괄호 ), ]", "color": "#d34097" },
	{ "tag": "SC", "desc": "구분자 , · / :", "color": "#901fbc" },
	{ "tag": "SY", "desc": "기타 기호", "color": "#b0e9c5" },
	{ "tag": "SH", "desc": "한자", "color": "#b8c196" },
	{ "tag": "SL", "desc": "외국어", "color": "#bd15ee" },
	{ "tag": "SN", "desc": "숫자", "color": "#a47a83" }
];

export default Tags;
