export const MorphTags = [
	{ "tag": "NN", "desc": "명사", "desc_eng": "Noun", "color": "#b24c4c" },
	{ "tag": "NNG", "desc": "일반 명사", "desc_eng": "Common Noun", "color": "#b24c4c" },
	{ "tag": "NNP", "desc": "고유 명사", "desc_eng": "Proper Noun", "color": "#b2554c" },
	{ "tag": "NNB", "desc": "의존 명사", "desc_eng": "Dependent Noun", "color": "#b25f4c" },
	{ "tag": "NP", "desc": "대명사", "desc_eng": "Pronoun", "color": "#b2684c" },
	{ "tag": "NR", "desc": "수사", "desc_eng": "Numeral", "color": "#b2724c" },
	{ "tag": "VV", "desc": "동사", "desc_eng": "Verb", "color": "#b27b4c" },
	{ "tag": "VA", "desc": "형용사", "desc_eng": "Adjective", "color": "#b2854c" },
	{ "tag": "VX", "desc": "보조 용언", "desc_eng": "Auxiliary Verb", "color": "#b28e4c" },
	{ "tag": "VC", "desc": "지정사", "desc_eng": "Copula", "color": "#b2984c" },
	{ "tag": "VCP", "desc": "긍정 지정사", "desc_eng": "Positive Copula", "color": "#b2984c" },
	{ "tag": "VCN", "desc": "부정 지정사", "desc_eng": "Negative Copula", "color": "#b2a14c" },
	{ "tag": "MM", "desc": "관형사", "desc_eng": "Determiner", "color": "#b2ab4c" },
	{ "tag": "MMA", "desc": "성상 관형사", "desc_eng": "Descriptive Determiner", "color": "#b2ab4c" },
	{ "tag": "MMD", "desc": "지시 관형사", "desc_eng": "Demonstrative Determiner", "color": "#b0b24c" },
	{ "tag": "MMN", "desc": "수 관형사", "desc_eng": "Numeral Determiner", "color": "#a6b24c" },
	{ "tag": "MA", "desc": "부사", "desc_eng": "Adverb", "color": "#9cb24c" },
	{ "tag": "MAG", "desc": "일반 부사", "desc_eng": "General Adverb", "color": "#9cb24c" },
	{ "tag": "MAJ", "desc": "접속 부사", "desc_eng": "Conjunctive Adverb", "color": "#93b24c" },
	{ "tag": "IC", "desc": "감탄사", "desc_eng": "Interjection", "color": "#8ab24c" },
	{ "tag": "JK", "desc": "격조사", "desc_eng": "Particle", "color": "#80b24c" },
	{ "tag": "JKS", "desc": "주격 조사", "desc_eng": "Subject Marker", "color": "#80b24c" },
	{ "tag": "JKC", "desc": "보격 조사", "desc_eng": "Complement Marker", "color": "#76b24c" },
	{ "tag": "JKG", "desc": "관형격 조사", "desc_eng": "Modifier Marker", "color": "#6db24c" },
	{ "tag": "JKO", "desc": "목적격 조사", "desc_eng": "Object Marker", "color": "#64b24c" },
	{ "tag": "JKB", "desc": "부사격 조사", "desc_eng": "Adverbial Marker", "color": "#5ab24c" },
	{ "tag": "JKV", "desc": "호격 조사", "desc_eng": "Vocative Marker", "color": "#50b24c" },
	{ "tag": "JKQ", "desc": "인용격 조사", "desc_eng": "Quotation Marker", "color": "#4cb250" },
	{ "tag": "JC", "desc": "접속 조사", "desc_eng": "Conjunction", "color": "#4cb25a" },
	{ "tag": "JX", "desc": "보조사", "desc_eng": "Auxiliary Particle", "color": "#4cb264" },
	{ "tag": "EM", "desc": "어미", "desc_eng": "Ending", "color": "#4cb26d" },
	{ "tag": "EP", "desc": "선어말 어미", "desc_eng": "Pre-final Ending", "color": "#4cb26d" },
	{ "tag": "EF", "desc": "종결 어미", "desc_eng": "Final Ending", "color": "#4cb276" },
	{ "tag": "EC", "desc": "연결 어미", "desc_eng": "Connective Ending", "color": "#4cb280" },
	{ "tag": "ETN", "desc": "명사형 전성 어미", "desc_eng": "Nominalizer", "color": "#4cb28a" },
	{ "tag": "ETM", "desc": "관형형 전성 어미", "desc_eng": "Adnominalizer", "color": "#4cb293" },
	{"tag": "XP", "desc": "접두사", "desc_eng": "Prefix", "color": "#4cb29c" },
	{ "tag": "XPN", "desc": "체언 접두사", "desc_eng": "Noun Prefix", "color": "#4cb29c" },
	{"tag": "XS", "desc": "접미사", "desc_eng": "Suffix", "color": "#4cb2a6" },
	{ "tag": "XSN", "desc": "명사 파생 접미사", "desc_eng": "Noun Suffix", "color": "#4cb2a6" },
	{ "tag": "XSV", "desc": "동사 파생 접미사", "desc_eng": "Verb Suffix", "color": "#4cb2b0" },
	{ "tag": "XSA", "desc": "형용사 파생 접미사", "desc_eng": "Adjective Suffix", "color": "#4cabb2" },
	{ "tag": "XR", "desc": "어근", "desc_eng": "Root", "color": "#4ca1b2" },
	{"tag": "ST", "desc": "기호", "desc_eng": "Symbol", "color": "#4c98b2" },
	{ "tag": "SF", "desc": "마침표, 물음표, 느낌표", "desc_eng": "Sentence-final Punctuation", "color": "#4c98b2" },
	{ "tag": "SC", "desc": "콤마, 가운뎃점, 콜론", "desc_eng": "Comma, Middle Dot, Colon", "color": "#4c98b2" },
	{ "tag": "SP", "desc": "쉼표, 가운뎃점, 콜론, 빗금", "desc_eng": "Comma, Middle Dot, Colon, Slash", "color": "#4c8eb2" },
	{ "tag": "SS", "desc": "따옴표, 괄호표, 줄표", "desc_eng": "Quotation Mark, Parenthesis, Dash", "color": "#4c85b2" },
	{ "tag": "SE", "desc": "줄임표", "desc_eng": "Ellipsis", "color": "#4c7bb2" },
	{ "tag": "SO", "desc": "붙임표(물결, 숨김, 빠짐)", "desc_eng": "Hyphen", "color": "#4c72b2" },
	{ "tag": "SW", "desc": "기타기호 (논리수학기호, 화폐기호)", "desc_eng": "Other Symbols (Math, Currency)", "color": "#4c68b2" },
	{ "tag": "SL", "desc": "외국어", "desc_eng": "Foreign Word", "color": "#4c5fb2" },
	{ "tag": "SH", "desc": "한자", "desc_eng": "Chinese Character", "color": "#4c55b2" },
	{ "tag": "SN", "desc": "숫자", "desc_eng": "Number", "color": "#4c4cb2" }
];



export const CohTags = {
	"lemma_NDW": "전체 형태소 타입 수(NDW)",
	"lemma_TTR": "전체 형태소 다양성, 타입-토큰 비율(TTR)",
	"lemma_MTTR": "50구간별 전체 형태소 다양성, 타입-토큰 비율(TTR)",
	"content_TTR": "실질 형태소 다양성, 타입-토큰 비율(TTR)",
	"formal_TTR": "형식 형태소 다양성, 타입-토큰 비율(TTR)",
	"noun_TTR": "명사 다양성, 타입-토큰 비율(TTR)",
	"VV_TTR": "동사 다양성, 타입-토큰 비율(TTR)",
	"VA_TTR": "형용사 다양성, 타입-토큰 비율(TTR)",
	"MA_TTR": "부사 다양성, 타입-토큰 비율(TTR)",
	"conjunction_TTR": "접속사 다양성, 타입-토큰 비율(TTR)",
	"ngram2_TTR": "전체 형태소 2-gram 다양성, 타입-토큰 비율(TTR)",
	"ngram3_TTR": "전체 형태소 3-gram 다양성, 타입-토큰 비율(TTR)",
	"ngram4_TTR": "전체 형태소 4-gram 다양성, 타입-토큰 비율(TTR)",
	"ngram5_TTR": "전체 형태소 5-gram 다양성, 타입-토큰 비율(TTR)",
	"ngram6_TTR": "전체 형태소 6-gram 다양성, 타입-토큰 비율(TTR)",
	"ngram7_TTR": "전체 형태소 7-gram 다양성, 타입-토큰 비율(TTR)",
	"ngram8_TTR": "전체 형태소 8-gram 다양성, 타입-토큰 비율(TTR)",
	"trigramLemma_TTR": "전체 형태소 trigram 다양성, 타입-토큰 비율(TTR)",
	"lexical_DensityTokens": "형태소 토큰 범위 참조 응집성",
	"lexical_DensityTypes": "형태소 타입의 참조 응집성",
	"avgSentSimilarity": "KeyBERT 주제 일관성",
	"topicConsistency": "SBERT 텍스트 내 문장 간 의미 유사도",
	"char_Cnt": "음절 수",
	"morph_Cnt": "형태소 수",
	"word_Cnt": "어절 수",
	"sentence_Cnt": "문장 수",
	"para_Cnt": "문단 수",
	"content_Cnt": "실질 형태소 수",
	"formal_Cnt": "형식 형태소 수",
	"substansive_Cnt": "체언 수",
	"noun_Cnt": "명사 수",
	"NNG_Cnt": "일반명사 수",
	"NNP_Cnt": "고유명사 수",
	"NNB_Cnt": "의존명사 수",
	"NP_Cnt": "대명사 수",
	"NPPeople_Cnt": "인칭대명사 수",
	"NPThings_Cnt": "지시대명사 수",
	"NR_Cnt": "수사 수",
	"verb_Cnt": "용언 수",
	"VV_Cnt": "동사 수",
	"VA_Cnt": "형용사 수",
	"VX_Cnt": "보조용언 수",
	"VCP_Cnt": "긍정 지정사(서술격조사) 수",
	"VCN_Cnt": "부정 지정사 수",
	"mod_Cnt": "수식언 수",
	"MM_Cnt": "관형사 수",
	"MA_Cnt": "부사 수",
	"J_Cnt": "관계언(조사) 수",
	"E_Cnt": "어미 수",
	"X_Cnt": "접사 수",
	"IC_Cnt": "독립언 수",
	"substansive_Lst": "체언 목록",
	"noun_Lst": "명사 목록",
	"NNG_Lst": "일반명사 목록",
	"NNP_Lst": "고유명사 목록",
	"NNB_Lst": "의존명사 목록",
	"NP_Lst": "대명사 목록",
	"NPPeople_Lst": "인칭대명사 목록",
	"NPThings_Lst": "지시대명사 목록",
	"NR_Lst": "수사 목록",
	"verb_Lst": "용언 목록",
	"VV_Lst": "동사 목록",
	"VA_Lst": "형용사 목록",
	"VX_Lst": "보조용언 목록",
	"VCP_Lst": "긍정 지정사(서술격조사) 목록",
	"VCN_Lst": "부정 지정사 목록",
	"mod_Lst": "수식언 목록",
	"MM_Lst": "관형사 목록",
	"MA_Lst": "부사 목록",
	"J_Lst": "조사 목록",
	"E_Lst": "어미 목록",
	"X_Lst": "접사 목록",
	"IC_Lst": "독립언 목록",
	"substansive_TTR": "체언 다양성, 타입-토큰 비율(TTR)",
	"NNG_TTR": "일반명사 다양성, 타입-토큰 비율(TTR)",
	"NNP_TTR": "고유명사 다양성, 타입-토큰 비율(TTR)",
	"NNB_TTR": "의존명사 다양성, 타입-토큰 비율(TTR)",
	"NP_TTR": "대명사 다양성, 타입-토큰 비율(TTR)",
	"NR_TTR": "수사 다양성, 타입-토큰 비율(TTR)",
	"verb_TTR": "용언 다양성, 타입-토큰 비율(TTR)",
	"mod_TTR": "수식언 다양성, 타입-토큰 비율(TTR)",
	"MM_TTR": "관형사 다양성, 타입-토큰 비율(TTR)",
	"IC_TTR": "독립언 다양성, 타입-토큰 비율(TTR)",
	"J_TTR": "조사 다양성, 타입-토큰 비율(TTR)",
	"E_TTR": "어미 다양성, 타입-토큰 비율(TTR)",
	"X_TTR": "접사 다양성, 타입-토큰 비율(TTR)",
	"CL_Den": "실질 형태소 밀도",
	"FL_Den": "형식 형태소 밀도",
	"NL_Den": "체언 밀도",
	"NCL_Den": "체언 실질 밀도",
	"NNL_Den": "명사 밀도",
	"NNCL_Den": "명사 실질 밀도",
	"NNGL_Den": "일반명사 밀도",
	"NNGCL_Den": "일반명사 실질 밀도",
	"NNPL_Den": "고유명사 밀도",
	"NNPCL_Den": "고유명사 실질 밀도",
	"NNBL_Den": "의존명사 밀도",
	"NNBCL_Den": "의존명사 실질 밀도",
	"NPL_Den": "대명사 밀도",
	"NPCL_Den": "대명사 실질 밀도",
	"NML_Den": "수사 밀도",
	"NMCL_Den": "수사 실질 밀도",
	"VL_Den": "용언 밀도",
	"VCL_Den": "용언 실질 밀도",
	"VVL_Den": "동사 밀도",
	"VVCL_Den": "동사 실질 밀도",
	"VAL_Den": "형용사 밀도",
	"VACL_Den": "형용사 실질 밀도",
	"ML_Den": "수식언 밀도",
	"MCL_Den": "수식언 실질 밀도",
	"MML_Den": "관형사 밀도",
	"MMCL_Den": "관형사 실질 밀도",
	"MAL_Den": "부사 밀도",
	"MACL_Den": "부사 실질 밀도",
	"ITL_Den": "독립언 밀도",
	"INCL_Den": "독립언 실질 밀도",
	"JL_Den": "조사 밀도",
	"JFL_Den": "조사 형식 밀도",
	"EL_Den": "어미 밀도",
	"EFL_Den": "어미 형식 밀도",
	"XL_Den": "접사 밀도",
	"XFL_Den": "접사 형식 밀도",
	"morph_LenAvg": "형태소 길이, 음절 수, 평균",
	"morph_LenStd": "형태소 길이, 음절 수, 표준편차",
	"word_LenAvg": "어절 길이, 음절 수, 평균",
	"word_LenStd": "어절 길이, 음절 수, 표준편차",
	"substansive_NDW": "체언 다양성, 타입 수(NDW)",
	"NNG_NDW": "일반명사 다양성, 타입 수(NDW)",
	"NNP_NDW": "고유명사 다양성, 타입 수(NDW)",
	"NNB_NDW": "의존명사 다양성, 타입 수(NDW)",
	"NP_NDW": "대명사 다양성, 타입 수(NDW)",
	"NR_NDW": "수사 다양성, 타입 수(NDW)",
	"verb_NDW": "용언 다양성, 타입 수(NDW)",
	"VV_NDW": "동사 다양성, 타입 수(NDW)",
	"VA_NDW": "형용사 다양성, 타입 수(NDW)",
	"mod_NDW": "수식언 다양성, 타입 수(NDW)",
	"MM_NDW": "관형사 다양성, 타입 수(NDW)",
	"IC_NDW": "독립언 다양성, 타입 수(NDW)",
	"J_NDW": "조사 다양성,타입 수(NDW)",
	"E_NDW": "어미 다양성,타입 수(NDW)",
	"X_NDW": "접사 다양성, 타입 수(NDW)",
	"CL_NDW": "실질 형태소 다양성, 타입 수(NDW)",
	"FL_NDW": "형식 형태소 다양성, 타입 수(NDW)",
	"lemma_RTTR": "전체 형태소 다양성, 타입-√토큰 비율(RTTR)(G)",
	"substansive_RTTR": "체언 다양성, 타입-√토큰 비율(RTTR)(G)",
	"NNG_RTTR": "일반명사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"NNP_RTTR": "고유명사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"NNB_RTTR": "의존명사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"NP_RTTR": "대명사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"NR_RTTR": "수사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"verb_RTTR": "용언 다양성, 타입-√토큰 비율(RTTR)(G)",
	"VV_RTTR": "동사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"VA_RTTR": "형용사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"mod_RTTR": "수식언 다양성, 타입-√토큰 비율(RTTR)(G)",
	"MM_RTTR": "관형사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"IC_RTTR": "독립언 다양성, 타입-√토큰 비율(RTTR)(G)",
	"J_RTTR": "조사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"E_RTTR": "어미 다양성, 타입-√토큰 비율(RTTR)(G)",
	"X_RTTR": "접사 다양성, 타입-√토큰 비율(RTTR)(G)",
	"CL_RTTR": "실질 형태소 다양성, 타입-√토큰 비율(RTTR)(G)",
	"FL_RTTR": "형식 형태소 다양성, 타입-√토큰 비율(RTTR)(G)",
	"lemma_CTTR": "전체 형태소 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"substansive_CTTR": "체언 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"NNG_CTTR": "일반명사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"NNP_CTTR": "고유명사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"NNB_CTTR": "의존명사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"NP_CTTR": "대명사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"NR_CTTR": "수사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"verb_CTTR": "용언 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"VV_CTTR": "동사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"VA_CTTR": "형용사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"mod_CTTR": "수식언 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"MM_CTTR": "관형사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"IC_CTTR": "독립언 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"J_CTTR": "조사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"E_CTTR": "어미 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"X_CTTR": "접사 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"CL_CTTR": "실질 형태소 다양성, 타입-√2*토큰 비율(CTTR)(G)",
	"FL_CTTR": "형식 형태소 다양성, 타입-√2*토큰 비율(CTTR)(G)",
};
