export const LABELS = {
    home: { ko: "홈", en: "Home" },
    analysis: { ko: "분석", en: "Analysis" },
    feedback: { ko: "피드백", en: "Feedback" },
    reset: { ko: "재설정", en: "Reset" },
    input: { ko: "텍스트 입력", en: "Input Korean Text" },
    input_kor: {ko: "분석할 텍스트 입력", en: "Input Korean Text to Analyze"},
    download: { ko: "다운로드", en: "Download" },
    compare: { ko: "비교", en: "Compare" },
    clear: { ko: "지우기", en: "Clear" },
    delete: { ko: "삭제", en: "Delete" },
    analysis_results: { ko: "분석 결과", en: "Analysis Results" },
    morpheme_tags: { ko: "형태소 태그", en: "Morpheme Tags" },
    tag_info: { ko: "태그 정보", en: "Tag Information" },
    tag_color: { ko: "태그 색상", en: "Tag Color" },
    tag: { ko: "태그", en: "Tag" },
    description: { ko: "설명", en: "Description" },
    description_eng: { ko: "영어 설명", en: "English Description" },
    file_chooser: { ko: "개의 파일 선택", en: " Files Selected" },
    Compare: { ko: "분석 결과 비교", en: "Compare" },
    Basic: {ko: "기초 정보", en: "Basic Information" },
    Cohesion: {ko: "응집성", en: "Cohesion" },
    sentence_level: {ko: "문장/문단 수준 분석", en: "Sentence/Paragraph Level Analysis" },
    morpheme_level: {ko: "형태소/단어 수준 분석", en: "Morpheme/Word Level Analysis" },
    text_level: {ko: "텍스트 분석", en: "Text Level Analysis" },
    writing_evaluation: {ko: "쓰기 채점", en: "Writing Evaluation" },
    morpheme_analysis: {ko: "형태소 분석", en: "Morpheme Analysis" },
    correction: {ko: "철자법/문법 교정", en: "Spelling/Grammar Correction" },
    vocabulary_grades: {ko: "어휘 등급 & 타입-토큰 목록", en: "Vocabulary Grades & Type-Token List" },
    morpheme_count: {ko: "문단/문장/단어/형태소 수", en: "Morpheme Count" },
    morpheme_list: {ko: "단어/형태소 목록", en: "Morpheme Lists" },
    morpheme_density: {ko: "단어/형태소 밀도", en: "Morpheme Density" },
    morpheme_len: {ko: "단어/형태소 길이", en: "Morpheme/Word Length" },
    lexical_TTR: {ko: "어휘 다양도(TTR)", en: "Lexical Diversity(TTR)" },
    lexical_NDW: {ko: "어휘 다양도(NDW)", en: "Lexical Diversity(NDW)" },
    sentence_complexity: {ko: "문장/문단 복잡도", en: "Sentence/Paragraph Complexity" },
    sentence_repetition: {ko: "문장/문단당 반복, 정형 표현", en: "Repetition, Standard Expression Per Sentence/Paragraph" },
    repetition_list: {ko: "반복, 정형 표현 목록", en: "Repetition, Standard Expression List" },
    adjacency_cohesion: {ko: "참조 응집성", en: "Adjacency Cohesion" },
    semantic_similarity: {ko: "문장 간 의미 유사성, 주제 일관성", en: "Semantic Similarity, Topic Consistancy" },
    readability_scores: {ko: "이독성", en: "Readability Scores" },
    Mor_download_csv: {ko: "형태소 분석 csv 다운로드", en: "Morpheme Analysis csv download" },
    Mor_download_json: {ko: "형태소 분석 json 다운로드", en: "Morpheme Analysis json download" },
    Cor_download_csv: {ko: "철자법/문법 교정 csv 다운로드 (Spelling/Grammar Correction csv)", en: "Spelling/Grammar Correction csv download" },
    Cor_download_json: {ko: "철자법/문법 교정 json 다운로드 (Spelling/Grammar Correction json)", en: "Spelling/Grammar Correction json download" },
    Voc_download_csv: {ko: "어휘 등급 csv 다운로드", en: "Vocabulary Grades csv download" },
    Voc_download_json: {ko: "어휘 등급 json 다운로드 (Vocabulary Grades json)", en: "Vocabulary Grades json download" },
    Basic_download_csv: {ko: "기초 정보 csv 다운로드 (Basic Information csv)", en: "Basic Information csv download" },
    Tag: {ko: "태그", en: "Tag" },
    Value: {ko: "값", en: "Value" },
    Target: {ko: "대상", en: "Target" },
    Description: {ko: "설명", en: "Description" },
    feature:{ko:"태그", en:"feature"},
    type:{ko:"자질", en:"Type"},
    type1:{ko:"타입", en:"Type"},
    Mor:{ko:"대상", en:"Morpheme"},
    choose_file: {ko: "파일 선택", en: "Choose File" },
    not_file: {ko: "선택된 파일 없음", en: "No file selected" },
    input_text: {ko: "텍스트를 입력하세요", en: "Input Korean Text" },
    revisions: {ko: "개의 수정 제안", en: "Possible Revisions"},
    total_score:{ko: '총점', en:"Total Score"},
    Korea_result: {ko:"한국어 텍스트 분석", en:"Korean Text Analysis"},
    past_result:{ko:"이전 분석 결과", en:"Past Results - Universal Anaysis"},
    top_k_indices: {ko:"상위 K개 자질", en:"Top-K Indices"},
    essay_score:{ko:"에세이 점수", en:"Essay Score"},
    score:{ko:"점수", en:"Score"},
    rubric:{ko:"루브릭", en:"Rubric"},
    feedback_main:{ko:"원문", en:"Original Text"},
    input_origin:{ko:"여기에 원문을 입력하세요.",en : "Type the main feedback here."},
    ai_fb:{ko:"AI 피드백", en:"AI Feedback"},
    fb_result:{ko:"피드백 내용이 출력됩니다.", en: "Display feedback content."},
    statistic:{ko:"통계 자료", en:"Statistic"},
    fb_gene:{ko:"  · 생성 중...", en:"· Generating..."},
    copy:{ko:"복사", en:"Copy"},
    stats_title: { ko: "통계 자료", en: "Statistics" },
    chars: { ko: "글자 수", en: "Characters" },
    sentences: { ko: "문장 수", en: "Sentences" },
    paragraphs: { ko: "문단 수", en: "Paragraphs" },
    avg_sentence_len: { ko: "평균 문장 길이", en: "Avg. sentence length" },
    quota_requirement: { ko: "과제 기준(≥600자)", en: "Requirement (≥600 chars)" },
    estimated_score_title: { ko: "예상 점수", en: "Estimated score" },

    // 통계 값 단위/표현
    chars_unit: { ko: "자(공백 제외)", en: " chars (no spaces)" },
    count_unit: { ko: "개", en: "" }, // 영어는 보통 단위 생략
    words_unit: { ko: "단어", en: "words" },
    quota_ok: { ko: "충족", en: "Met" },
    quota_fail: { ko: "미충족", en: "Not met" },

    // 렌더링 빈 콘텐츠 메시지
    no_content: { ko: "표시할 내용이 없습니다.", en: "No content to display." },

    // 어휘 등급(사고도구어) 분포
    lex_dist_title: { ko: "사고도구어 수준 분포", en: "Lexical level distribution" },
    lex_dist_note: {
      ko: "※ 분포는 분석 결과의 voc_grades(등장 빈도 가중) 기준입니다.",
      en: "※ Distribution is based on voc_grades (frequency-weighted).",
    },
    level_1: { ko: "1수준", en: "Level 1" },
    level_2: { ko: "2수준", en: "Level 2" },
    level_3: { ko: "3수준", en: "Level 3" },
    level_4: { ko: "4수준", en: "Level 4" },
    level_5: { ko: "5수준", en: "Level 5" },

    }

  //import { LABELS } from "../labels";
  //{LABELS.input[language]}