export const MorphTags = [
	{ "tag": "NNG", "desc": "일반 명사", "desc_eng": "Common Noun", "color": "#b24c4c" },
	{ "tag": "NNP", "desc": "고유 명사", "desc_eng": "Proper Noun", "color": "#b2554c" },
	{ "tag": "NNB", "desc": "의존 명사", "desc_eng": "Dependent Noun", "color": "#b25f4c" },
	{ "tag": "NP", "desc": "대명사", "desc_eng": "Pronoun", "color": "#b2684c" },
	{ "tag": "NR", "desc": "수사", "desc_eng": "Numeral", "color": "#b2724c" },
	{ "tag": "VV", "desc": "동사", "desc_eng": "Verb", "color": "#b27b4c" },
	{ "tag": "VA", "desc": "형용사", "desc_eng": "Adjective", "color": "#b2854c" },
	{ "tag": "VX", "desc": "보조 용언", "desc_eng": "Auxiliary Verb", "color": "#b28e4c" },
	{ "tag": "VC", "desc": "지정사", "desc_eng": "Copula", "color": "#b2984c" },
	{ "tag": "VCP", "desc": "긍정 지정사", "desc_eng": "Positive Copula", "color": "#b2984c" },
	{ "tag": "VCN", "desc": "부정 지정사", "desc_eng": "Negative Copula", "color": "#b2a14c" },
	{ "tag": "MM", "desc": "관형사", "desc_eng": "Determiner", "color": "#b2ab4c" },
	{ "tag": "MMA", "desc": "성상 관형사", "desc_eng": "Descriptive Determiner", "color": "#b2ab4c" },
	{ "tag": "MMD", "desc": "지시 관형사", "desc_eng": "Demonstrative Determiner", "color": "#b0b24c" },
	{ "tag": "MMN", "desc": "수 관형사", "desc_eng": "Numeral Determiner", "color": "#a6b24c" },
	{ "tag": "MA", "desc": "부사", "desc_eng": "Adverb", "color": "#9cb24c" },
	{ "tag": "MAG", "desc": "일반 부사", "desc_eng": "General Adverb", "color": "#9cb24c" },
	{ "tag": "MAJ", "desc": "접속 부사", "desc_eng": "Conjunctive Adverb", "color": "#93b24c" },
	{ "tag": "IC", "desc": "감탄사", "desc_eng": "Interjection", "color": "#8ab24c" },
	{ "tag": "J", "desc": "조사", "desc_eng": "Particle", "color": "#80b24c" },
	{ "tag": "JK", "desc": "격조사", "desc_eng": "Particle", "color": "#80b24c" },
	{ "tag": "JKS", "desc": "주격 조사", "desc_eng": "Subject Marker", "color": "#80b24c" },
	{ "tag": "JKC", "desc": "보격 조사", "desc_eng": "Complement Marker", "color": "#76b24c" },
	{ "tag": "JKG", "desc": "관형격 조사", "desc_eng": "Modifier Marker", "color": "#6db24c" },
	{ "tag": "JKO", "desc": "목적격 조사", "desc_eng": "Object Marker", "color": "#64b24c" },
	{ "tag": "JKB", "desc": "부사격 조사", "desc_eng": "Adverbial Marker", "color": "#5ab24c" },
	{ "tag": "JKV", "desc": "호격 조사", "desc_eng": "Vocative Marker", "color": "#50b24c" },
	{ "tag": "JKQ", "desc": "인용격 조사", "desc_eng": "Quotation Marker", "color": "#4cb250" },
	{ "tag": "JC", "desc": "접속 조사", "desc_eng": "Conjunction", "color": "#4cb25a" },
	{ "tag": "JX", "desc": "보조사", "desc_eng": "Auxiliary Particle", "color": "#4cb264" },
	{ "tag": "E", "desc": "어미", "desc_eng": "Ending", "color": "#4cb26d" },
	{ "tag": "EF", "desc": "종결 어미", "desc_eng": "Final Ending", "color": "#4cb26d" },
	{ "tag": "EP", "desc": "선어말 어미", "desc_eng": "Pre-final Ending", "color": "#4cb26d" },
	{ "tag": "EC", "desc": "연결 어미", "desc_eng": "Connective Ending", "color": "#4cb280" },
	{ "tag": "ETN", "desc": "명사형 전성 어미", "desc_eng": "Nominalizer", "color": "#4cb28a" },
	{ "tag": "ETM", "desc": "관형형 전성 어미", "desc_eng": "Adnominalizer", "color": "#4cb293" },
	{ "tag": "X", "desc": "접사", "desc_eng": "Affix", "color": "#4cb29c" },
	{ "tag": "XP", "desc": "접두사", "desc_eng": "Prefix", "color": "#4cb29c" },
	{ "tag": "XPN", "desc": "체언 접두사", "desc_eng": "Noun Prefix", "color": "#4cb29c" },
	{ "tag": "XS", "desc": "접미사", "desc_eng": "Suffix", "color": "#4cb2a6" },
	{ "tag": "XSN", "desc": "명사 파생 접미사", "desc_eng": "Noun Suffix", "color": "#4cb2a6" },
	{ "tag": "XSV", "desc": "동사 파생 접미사", "desc_eng": "Verb Suffix", "color": "#4cb2b0" },
	{ "tag": "XSA", "desc": "형용사 파생 접미사", "desc_eng": "Adjective Suffix", "color": "#4cabb2" },
	{ "tag": "XR", "desc": "어근", "desc_eng": "Root", "color": "#4ca1b2" },
	{ "tag": "ST", "desc": "기호", "desc_eng": "Symbol", "color": "#4c98b2" },
	{ "tag": "SF", "desc": "마침표, 물음표, 느낌표", "desc_eng": "Sentence-final Punctuation", "color": "#4c98b2" },
	{ "tag": "SC", "desc": "콤마, 가운뎃점, 콜론", "desc_eng": "Comma, Middle Dot, Colon", "color": "#4c98b2" },
	{ "tag": "SP", "desc": "쉼표, 가운뎃점, 콜론, 빗금", "desc_eng": "Comma, Middle Dot, Colon, Slash", "color": "#4c8eb2" },
	{ "tag": "SS", "desc": "따옴표, 괄호표, 줄표", "desc_eng": "Quotation Mark, Parenthesis, Dash", "color": "#4c85b2" },
	{ "tag": "SE", "desc": "줄임표", "desc_eng": "Ellipsis", "color": "#4c7bb2" },
	{ "tag": "SO", "desc": "붙임표(물결, 숨김, 빠짐)", "desc_eng": "Hyphen", "color": "#4c72b2" },
	{ "tag": "SW", "desc": "기타기호 (논리수학기호, 화폐기호)", "desc_eng": "Other Symbols (Math, Currency)", "color": "#4c68b2" },
	{ "tag": "SL", "desc": "외국어", "desc_eng": "Foreign Word", "color": "#4c5fb2" },
	{ "tag": "SH", "desc": "한자", "desc_eng": "Chinese Character", "color": "#4c55b2" },
	{ "tag": "SN", "desc": "숫자", "desc_eng": "Number", "color": "#4c4cb2" },

	{ "tag": "NN", "desc": "명사", "desc_eng": "Noun", "color": "#000000" },
	{ "tag": "NPP", "desc": "대명사 (인물)", "desc_eng": "Pronoun (People)", "color": "#000000" },
	{ "tag": "NPT", "desc": "대명사 (사물)", "desc_eng": "Pronoun (Things)", "color": "#000000" },
	{ "tag": "C", "desc": "실질", "desc_eng": "Content", "color": "#000000" },
	{ "tag": "N", "desc": "체언", "desc_eng": "Noun", "color": "#000000" },
	{ "tag": "M", "desc": "수식언", "desc_eng": "Modifier", "color": "#000000" },
	{ "tag": "NM", "desc": "수사", "desc_eng": "Rhetorical", "color": "#000000" },
	{ "tag": "F", "desc": "형식", "desc_eng": "Formal", "color": "#000000" },
	{ "tag": "V", "desc": "용언", "desc_eng": "Verb", "color": "#000000" },
	{ "tag": "IN", "desc": "독립언", "desc_eng": "Independant", "color": "#000000" },
	{ "tag": "IT", "desc": "독립언", "desc_eng": "Independant", "color": "#000000" },

	{ "tag": "lemma", "desc": "렘마", "desc_eng": "Lemma", "color": "#000000" },
	{ "tag": "morph", "desc": "형태소", "desc_eng": "Morpheme", "color": "#000000" },
	{ "tag": "word", "desc": "어절", "desc_eng": "Word", "color": "#000000" },
	{ "tag": "para", "desc": "문단", "desc_eng": "Paragraph", "color": "#000000" },
	{ "tag": "sentence", "desc": "문장", "desc_eng": "Sentence", "color": "#000000" },
	{ "tag": "sent", "desc": "문장", "desc_eng": "Sentence", "color": "#000000" },
	{ "tag": "char", "desc": "문자", "desc_eng": "Character", "color": "#000000" },
	{ "tag": "text", "desc": "텍스트", "desc_eng": "Text", "color": "#000000" },
];

export const CohTags = {
	"TTR": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "타입-토큰 비율",
		"desc_eng": "Type-Token Ratio",
	},
	"RTTR": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "타입-√토큰 비율",
		"desc_eng": "Root Type-Token Ratio",
	},
	"CTTR": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "타입-√2토큰 비율",
		"desc_eng": "Type-Token Ratio with Root 2",
	},
	"MSTTR": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "50구간별 타입-토큰 비율 평균",
		"desc_eng": "Mean Segmental Type-Token Ratio",
	},
	"MATTR": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "50구간별 타입-토큰 비율 평균 (중첩 허용)",
		"desc_eng": "Mean Average Type-Token Ratio",
	},
	"MTLD": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "토큰/Factor 수",
		"desc_eng": "Token/Factor Count",
	},
	"HDD": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "무작위 타입의 출현 확률",
		"desc_eng": "Hypergeometric Distribution Diversity",
	},
	"VOCDD": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "35-50개 토큰 100개 무작위 추출 TTR 평균",
		"desc_eng": "35-50 tokens, 100 random samples, average TTR",
	},
	"NDW": {
		"type": "어휘 다양성",
		"type_eng": "Lexical Diversity",
		"desc": "어절 다양성",
		"desc_eng": "Number of Different Words",
	},
	"Den": {
		"type": "어휘 밀도",
		"type_eng": "Basic",
		"desc": "형태소/어절 밀도",
		"desc_eng": "Density",
	},
	"C_Den": {
		"type": "어휘 밀도",
		"type_eng": "Basic",
		"desc": "형태소/어절 실질 밀도",
		"desc_eng": "Density",
	},
	"F_Den": {
		"type": "어휘 밀도",
		"type_eng": "Basic",
		"desc": "형태소/어절 형식 밀도",
		"desc_eng": "Density",
	},
	"Cnt": {
		"type": "기초",
		"type_eng": "Basic",
		"desc": "수",
		"desc_eng": "Count",
	},
	"Lst": {
		"type": "기초",
		"type_eng": "Basic",
		"desc": "해당 목록",
		"desc_eng": "List",
	},
	"LenAvg": {
		"type": "기초",
		"type_eng": "Basic",
		"desc": "평균 길이",
		"desc_eng": "Average Length",
	},
	"LenStd": {
		"type": "기초",
		"type_eng": "Basic",
		"desc": "표준편차",
		"desc_eng": "Standard Deviation",
	},
	"sentLen": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "타겟 기준 문장 길이",
		"desc_eng": "Sentence Length",
	},
	"sentLenAvg": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "타겟 기준 문장 평균 길이",
		"desc_eng": "Average Sentence Length",
	},
	"sentLenStd": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "타겟 기준 문장 길이 표준편차",
		"desc_eng": "Sentence Length Standard Deviation",
	},
	"paraLen": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "타겟 기준 문단 길이",
		"desc_eng": "Paragraph Length",
	},
	"paraLenAvg": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "타겟 기준 문단 평균 길이",
		"desc_eng": "Average Paragraph Length",
	},
	"paraLenStd": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "타겟 기준 문단 길이 표준편차",
		"desc_eng": "Paragraph Length Standard Deviation",
	},
	"sentCnt": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 수",
		"desc_eng": "Sentence Count",
	},
	"sentCntStd": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 수 표준편차",
		"desc_eng": "Sentence Count Standard Deviation",
	},
	"paraCnt": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 수",
		"desc_eng": "Paragraph Count",
	},
	"paraCntStd": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 수 표준편차",
		"desc_eng": "Paragraph Count Standard Deviation",
	},
	"sentPerPara": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 문장 수",
		"desc_eng": "Sentences per Paragraph",
	},
	"sentPerParaStd": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 문장 수 표준편차",
		"desc_eng": "Sentences per Paragraph Standard Deviation",
	},
	"wordPerSent": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 당 어절 수",
		"desc_eng": "Words per Sentence",
	},
	"wordPerSentStd": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 당 어절 수 표준편차",
		"desc_eng": "Words per Sentence Standard Deviation",
	},
	"wordPerPara": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 어절 수",
		"desc_eng": "Words per Paragraph",
	},
	"wordPerParaStd": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 어절 수 표준편차",
		"desc_eng": "Words per Paragraph Standard Deviation",
	},
	"charPerWord": {
		"type": "어절 복잡도",
		"type_eng": "Word Complexity",
		"desc": "어절 당 글자 수",
		"desc_eng": "Characters per Word",
	},
	"charPerWordStd": {
		"type": "어절 복잡도",
		"type_eng": "Word Complexity",
		"desc": "어절 당 글자 수 표준편차",
		"desc_eng": "Characters per Word Standard Deviation",
	},
	"wordLen": {
		"type": "어절 복잡도",
		"type_eng": "Word Complexity",
		"desc": "타겟 기준 어절 길이",
		"desc_eng": "Word Length",
	},
	"wordLenAvg": {
		"type": "어절 복잡도",
		"type_eng": "Word Complexity",
		"desc": "타겟 기준 어절 평균 길이",
		"desc_eng": "Average Word Length",
	},
	"wordLenStd": {
		"type": "어절 복잡도",
		"type_eng": "Word Complexity",
		"desc": "타겟 기준 어절 길이 표준편차",
		"desc_eng": "Word Length Standard Deviation",
	},
	"sentPuncCnt": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 당 문장부호 수",
		"desc_eng": "Punctuation per Sentence",
	},
	"sentPuncCntStd": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 당 문장부호 수 표준편차",
		"desc_eng": "Punctuation per Sentence Standard Deviation",
	},
	"paraPuncCnt": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 문장부호 수",
		"desc_eng": "Punctuation per Paragraph",
	},
	"paraPuncCntStd": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 문장부호 수 표준편차",
		"desc_eng": "Punctuation per Paragraph Standard Deviation",
	},
	"sentClauseCnt": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 당 절 수",
		"desc_eng": "Clauses per Sentence",
	},
	"sentClauseCntStd": {
		"type": "문장 복잡도",
		"type_eng": "Sentence Complexity",
		"desc": "문장 당 절 수 표준편차",
		"desc_eng": "Clauses per Sentence Standard Deviation",
	},
	"paraClauseCnt": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 절 수",
		"desc_eng": "Clauses per Paragraph",
	},
	"paraClauseCntStd": {
		"type": "문단 복잡도",
		"type_eng": "Paragraph Complexity",
		"desc": "문단 당 절 수 표준편차",
		"desc_eng": "Clauses per Paragraph Standard Deviation",
	},
	"sentCohesion": {
		"type": "문장 응집성",
		"type_eng": "Sentence Cohesion",
		"desc": "문장간 응집성",
		"desc_eng": "Inter-sentence Cohesion",
	},
	"sentCohesionStd": {
		"type": "문장 응집성",
		"type_eng": "Sentence Cohesion",
		"desc": "문장간 응집성 표준편차",
		"desc_eng": "Inter-sentence Cohesion Standard Deviation",
	},
	"paraCohesion": {
		"type": "문단 응집성",
		"type_eng": "Paragraph Cohesion",
		"desc": "문단간 응집성",
		"desc_eng": "Inter-paragraph Cohesion",
	},
	"paraCohesionStd": {
		"type": "문단 응집성",
		"type_eng": "Paragraph Cohesion",
		"desc": "문단간 응집성 표준편차",
		"desc_eng": "Inter-paragraph Cohesion Standard Deviation",
	},
	"sentTopic": {
		"type": "문장 주제성",
		"type_eng": "Sentence Topic",
		"desc": "문장 주제성",
		"desc_eng": "Sentence Topic",
	},
	"sentTopicStd": {
		"type": "문장 주제성",
		"type_eng": "Sentence Topic",
		"desc": "문장 주제성 표준편차",
		"desc_eng": "Sentence Topic Standard Deviation",
	},
	"paraTopic": {
		"type": "문단 주제성",
		"type_eng": "Paragraph Topic",
		"desc": "문단 주제성",
		"desc_eng": "Paragraph Topic",
	},
	"paraTopicStd": {
		"type": "문단 주제성",
		"type_eng": "Paragraph Topic",
		"desc": "문단 주제성 표준편차",
		"desc_eng": "Paragraph Topic Standard Deviation",
	},
	"paraTopicChg": {
		"type": "문단 주제성",
		"type_eng": "Paragraph Topic",
		"desc": "문단 주제성 변화량",
		"desc_eng": "Paragraph Topic Change",
	},
	"paraTopicChgStd": {
		"type": "문단 주제성",
		"type_eng": "Paragraph Topic",
		"desc": "문단 주제성 변화량 표준편차",
		"desc_eng": "Paragraph Topic Change Standard Deviation",
	},
	"sentSimilarity": {
		"type": "문장 유사도",
		"type_eng": "Sentence Similarity",
		"desc": "문장간 유사도",
		"desc_eng": "Inter-sentence Similarity",
	},
	"sentSimilarityStd": {
		"type": "문장 유사도",
		"type_eng": "Sentence Similarity",
		"desc": "문장간 유사도 표준편차",
		"desc_eng": "Inter-sentence Similarity Standard Deviation",
	},
	"paraSimilarity": {
		"type": "문단 유사도",
		"type_eng": "Paragraph Similarity",
		"desc": "문단간 유사도",
		"desc_eng": "Inter-paragraph Similarity",
	},
	"paraSimilarityStd": {
		"type": "문단 유사도",
		"type_eng": "Paragraph Similarity",
		"desc": "문단간 유사도 표준편차",
		"desc_eng": "Inter-paragraph Similarity Standard Deviation",
	},
	"sentSimilarityChg": {
		"type": "문장 유사도",
		"type_eng": "Sentence Similarity",
		"desc": "문장간 유사도 변화량",
		"desc_eng": "Inter-sentence Similarity Change",
	},
	"sentSimilarityChgStd": {
		"type": "문장 유사도",
		"type_eng": "Sentence Similarity",
		"desc": "문장간 유사도 변화량 표준편차",
		"desc_eng": "Inter-sentence Similarity Change Standard Deviation",
	},
	"paraSimilarityChg": {
		"type": "문단 유사도",
		"type_eng": "Paragraph Similarity",
		"desc": "문단간 유사도 변화량",
		"desc_eng": "Inter-paragraph Similarity Change",
	},
	"paraSimilarityChgStd": {
		"type": "문단 유사도",
		"type_eng": "Paragraph Similarity",
		"desc": "문단간 유사도 변화량 표준편차",
		"desc_eng": "Inter-paragraph Similarity Change Standard Deviation",
	},
	"sentCohesionChg": {
		"type": "문장 응집성",
		"type_eng": "Sentence Cohesion",
		"desc": "문장간 응집성 변화량",
		"desc_eng": "Inter-sentence Cohesion Change",
	},
	"sentCohesionChgStd": {
		"type": "문장 응집성",
		"type_eng": "Sentence Cohesion",
		"desc": "문장간 응집성 변화량 표준편차",
		"desc_eng": "Inter-sentence Cohesion Change Standard Deviation",
	},
	"paraCohesionChg": {
		"type": "문단 응집성",
		"type_eng": "Paragraph Cohesion",
		"desc": "문단간 응집성 변화량",
		"desc_eng": "Inter-paragraph Cohesion Change",
	},
	"paraCohesionChgStd": {
		"type": "문단 응집성",
		"type_eng": "Paragraph Cohesion",
		"desc": "문단간 응집성 변화량 표준편차",
		"desc_eng": "Inter-paragraph Cohesion Change Standard Deviation",
	},
	"sentCohesionTopicChg": {
		"type": "문장 응집성",
		"type_eng": "Sentence Cohesion",
		"desc": "문장간 응집성/주제성 변화량",
		"desc_eng": "Inter-sentence Cohesion/Topic Change",
	},
	"sentCohesionTopicChgStd": {
		"type": "문장 응집성",
		"type_eng": "Sentence Cohesion",
		"desc": "문장간 응집성/주제성 변화량 표준편차",
		"desc_eng": "Inter-sentence Cohesion/Topic Change Standard Deviation",
	},
	"paraCohesionTopicChg": {
		"type": "문단 응집성",
		"type_eng": "Paragraph Cohesion",
		"desc": "문단간 응집성/주제성 변화량",
		"desc_eng": "Inter-paragraph Cohesion/Topic Change",
	},
	"paraCohesionTopicChgStd": {
		"type": "문단 응집성",
		"type_eng": "Paragraph Cohesion",
		"desc": "문단간 응집성/주제성 변화량 표준편차",
		"desc_eng": "Inter-paragraph Cohesion/Topic Change Standard Deviation",
	},

	"score": {
		"alias": "score",
		"type": "점수",
		"type_eng": "Score",
		"desc": "점수",
		"desc_eng": "Score",
	},

	"grade_4_ratio": {
	"alias": "grade_4_ratio",
	"type": "어휘 등급",
	"type_eng": "Vocab Grade",
	"desc": "4등급 비율",
	"desc_eng": "Ratio of Grade 4",
	},

	"grade_3_ratio": {
	"alias": "grade_3_ratio",
	"type": "어휘 등급",
	"type_eng": "Vocab Grade",
	"desc": "3등급 비율",
	"desc_eng": "Ratio of Grade 3",
	},

	"grade_2_ratio": {
	"alias": "grade_2_ratio",
	"type": "어휘 등급",
	"type_eng": "Vocab Grade",
	"desc": "2등급 비율",
	"desc_eng": "Ratio of Grade 2",
	},

	"grade_m1_ratio": {
	"alias": "grade_m1_ratio",
	"type": "어휘 등급",
	"type_eng": "Vocab Grade",
	"desc": "NA 등급 비율",
	"desc_eng": "Ratio of Grade NA",
	},
}

export const EssayTags = {
	"grammar": {
		"type": "표현",
		"type_eng": "Expression",
		"desc": "규범",
		"desc_eng": "Grammar",
	},
	// (내부 계산용 유지)
	"vocabulary": {
		"type": "표현",
		"type_eng": "Expression",
		"desc": "어휘",
		"desc_eng": "Vocabulary",
	},
	// (내부 계산용 유지)
	"sentence_expression": {
		"type": "표현",
		"type_eng": "Expression",
		"desc": "문장 표현",
		"desc_eng": "Sentence Expression",
	},
	// ✅ 표/레이더에서 사용하는 통합 루브릭
	"vocab_sentence": {
		"type": "표현",
		"type_eng": "Expression",
		"desc": "어휘와 문장",
		"desc_eng": "Vocabulary & Sentence",
	},
	"intra_paragraph_structure": {
		"type": "조직",
		"type_eng": "Organization",
		"desc": "문단 내 조직",
		"desc_eng": "In-paragraph Structure",
	},
	"inter_paragraph_structure": {
		"type": "조직",
		"type_eng": "Organization",
		"desc": "글 전체 조직",
		"desc_eng": "Inter-paragraph Structure",
	},
	"structural_consistency": {
		"type": "조직",
		"type_eng": "Organization",
		"desc": "구조적 일관성",
		"desc_eng": "Structural Consistency",
	},
	"length": {
		"type": "조직",
		"type_eng": "Organization",
		"desc": "길이",
		"desc_eng": "Length",
	},
	"topic_clarity": {
		"type": "내용",
		"type_eng": "Content",
		"desc": "주장",
		"desc_eng": "Topic Clarity",
	},
	"originality": {
		"type": "내용",
		"type_eng": "Content",
		"desc": "다른 입장 고려",
		"desc_eng": "Originality",
	},

	"Topic_relevance": {
		"type": "주제 적합성",
		"type_eng": "Topic relevance",
		"desc": "제시된 주제와의 관련성",
		"desc_eng": "Relevance to the given topic"
	},

	"narrative": {
		"type": "내용",
		"type_eng": "Content",
		"desc": "이유와 근거",
		"desc_eng": "Narrative",
	},
	// "prompt_comprehension": {
	// 	"type": "내용 Content",
	// 	"desc": "주제 이해 Prompt Comprehension",
	// },

	// "narrative": {
	// 	"type": "내용",
	// 	"type_eng": "Content",
	// 	"desc": "서사",
	// 	"desc_eng": "Narrative",
	// }
}